# Generated by Django 5.2.4 on 2025-07-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compañia', 'verbose_name_plural': 'Compañias'},
        ),
    ]
