# Generated by Django 5.2.4 on 2025-07-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='Nombre de la compañia'),
            preserve_default=False,
        ),
    ]
