# Generated by Django 5.2.4 on 2025-07-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='company/image')),
            ],
            options={
                'verbose_name': 'Empresa/compañía',
                'verbose_name_plural': 'Empresas/compañías',
            },
        ),
    ]
